name: Deploy to Amazon ECR

on:
  push:
    branches:
      - main

env:
  REPO_NAME: simple-react
  REGION: ap-south-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Get AWS account ID
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
          echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV

      - name: Create ECR repository if it doesn't exist
        run: |
          if ! aws ecr describe-repositories --region $REGION --repository-names $REPO_NAME --output text; then
            aws ecr create-repository --region $REGION --repository-name $REPO_NAME
          fi
          REPO_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME
          echo "REPO_URI=$REPO_URI" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t $REPO_URI:latest .
          docker tag $REPO_URI:latest $REPO_URI:$(git rev-parse --short HEAD)
          docker push $REPO_URI:latest
          docker push $REPO_URI:$(git rev-parse --short HEAD)

      - name: Verify deployment
        run: |
          echo "Deployment successful"
